version: "3.3"
services:
  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    command: uvicorn raddar.main:app --host 0.0.0.0 --port 80

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    volumes:
      - pg-admin-db-data:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.fr
      - PGADMIN_DEFAULT_PASSWORD=admin # pragma: allowlist secret
    ports:
      - "5050:80"

  db:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # pragma: allowlist secret
      - POSTGRES_DB=raddar

  worker:
    depends_on:
      - db
      - queue
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery -A raddar.core.celery_app worker -l info -c 1

  queue:
    image: rabbitmq:latest

  flower:
    image: mher/flower:0.9.4
    env_file:
      - .env
    ports:
      - "5555:5555"
    command:
      - "--broker=amqp://guest@queue:5672//"

volumes:
  app-db-data:
  pg-admin-db-data:
