version: "3.7"
services:

  backend:
    depends_on:
      - db
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    command: bash -c "uvicorn raddar.main:app --host 0.0.0.0 --port 80"
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    volumes:
      - app-db-data:/root/.pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
  
  db:
    image: postgres:13
    volumes:
      - pg-admin-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres # pragma: allowlist secret
      - POSTGRES_DB=raddar

  worker:
    depends_on:
      - db
      - queue
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery -A raddar.core.celery_app worker -l info -c 1
  
  queue:
    image: rabbitmq:latest
  
  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - "5555:5555"
    command:
      - "--broker=amqp://guest@queue:5672//"

volumes:
  app-db-data:
  pg-admin-db-data: